collections:
  notes:
    output: true
    permalink: /notes/:name/
  news:
    output: true
    permalink: /news/:name/

defaults:
  - scope:
      path: ""
      type: notes
    values:
      layout: note
  - scope:
      path: ""
      type: news
    values:
      layout: note
